package io.github.maze11.messages;

import com.badlogic.ashley.core.Entity;

/** Represents a message generated by an interactable object when the player collides with it.
 * Specific interactables should use either this as a base class, or call the constructor directly if no additional
 * information needs to be transferred
 */
public class InteractableMessage extends Message implements Cloneable{

    /** The player that interacted with the interactable */
    private Entity player;
    /** The interactable that activated */
    private Entity interactable;

    public InteractableMessage(MessageType type) {
        super(type);
    }

    /** Returns the player that interacted with the interactable */
    public Entity getPlayer() {
        return player;
    }

    /** Returns the interactable that was activated */
    public Entity getInteractable() {
        return interactable;
    }

    /** Sets the data of this message. Used when the interaction occurs to store data in the message */
    public void specifyInteraction(Entity player, Entity interactable){
        this.player = player;
        this.interactable = interactable;
    }

    /** Shallow copies the object */
    public Object clone(){
        try {
            return (InteractableMessage) super.clone();
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
    }
}
