package io.github.maze11.messages;

import com.badlogic.ashley.core.Entity;

/** Represents a message generated by an interactable object when the player collides with it.
 * Specific interactables should use either this as a base class, or call the constructor directly if no additional
 * information needs to be transferred
 */
public class InteractableMessage extends Message implements Cloneable{

    private Entity player;
    private Entity interactable;

    public InteractableMessage(MessageType type) {
        super(type);
    }

    public Entity getPlayer() {
        return player;
    }

    public Entity getInteractable() {
        return interactable;
    }

    public void specifyInteraction(Entity player, Entity interactable){
        this.player = player;
        this.interactable = interactable;
    }

    public Object clone(){
        try {
            return (InteractableMessage) super.clone();
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
    }
}
